# 01 — Data Cleaning

**Project:** Enterprise Marketing Analytics & Customer 360 Platform  
**Dataset:** Olist Brazilian E-Commerce  
**Status:** Complete — raw CSVs in `data/raw/`, cleaned outputs in `data/processed/`

## Objectives
1. Load raw Olist CSVs
2. Inspect schema, nulls, and data types
3. Clean timestamps, categories, and prices
4. Export cleaned tables to `data/processed/`

## Sections
- [x] Setup and paths
- [x] Run cleaning pipeline (`src/data_cleaning.py`)
- [x] Data quality summary
- [x] Export processed files

In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path('..').resolve()
sys.path.insert(0, str(PROJECT_ROOT / 'src'))

from data_cleaning import run_cleaning_pipeline

tables = run_cleaning_pipeline()
quality = tables['data_quality_report']
quality

Loading raw Olist files from data/raw/ ...
Exported: /Users/angollapraveengoud/Desktop/enterprise-marketing-analytics-platform/data/processed/orders.csv (99,441 rows)
Exported: /Users/angollapraveengoud/Desktop/enterprise-marketing-analytics-platform/data/processed/order_items.csv (112,650 rows)
Exported: /Users/angollapraveengoud/Desktop/enterprise-marketing-analytics-platform/data/processed/products.csv (32,951 rows)
Exported: /Users/angollapraveengoud/Desktop/enterprise-marketing-analytics-platform/data/processed/customers.csv (99,441 rows)
Exported: /Users/angollapraveengoud/Desktop/enterprise-marketing-analytics-platform/data/processed/reviews.csv (99,224 rows)
Exported: /Users/angollapraveengoud/Desktop/enterprise-marketing-analytics-platform/data/processed/payments.csv (103,886 rows)
Exported: /Users/angollapraveengoud/Desktop/enterprise-marketing-analytics-platform/data/processed/data_quality_report.csv (11 rows)

Data quality summary:
      table                      metric     value
     orders                   row_count  99441.00
     orders               delivered_pct     97.02
     orders delayed_among_delivered_pct      6.77
order_items                   row_count 112650.00
order_items         invalid_price_count      0.00
   products                   row_count  32951.00
   products        unknown_category_pct      1.85
  customers                   row_count  99441.00
  customers            unique_customers  96096.00
    reviews                   row_count  99224.00
    reviews         invalid_score_count      0.00

          table                       metric      value
0        orders                    row_count   99441.00
1        orders                delivered_pct      97.02
2        orders  delayed_among_delivered_pct       6.77
3   order_items                    row_count  112650.00
4   order_items          invalid_price_count       0.00
5      products                    row_count   32951.00
6      products         unknown_category_pct       1.85
7     customers                    row_count   99441.00
8     customers             unique_customers   96096.00
9       reviews                    row_count   99224.00
10      reviews          invalid_score_count       0.00

In [2]:
import pandas as pd

processed = Path('../data/processed')
for name in ['orders', 'order_items', 'products', 'customers', 'reviews']:
    df = pd.read_csv(processed / f'{name}.csv', nrows=3)
    print(f'\n=== {name} ({len(pd.read_csv(processed / f"{name}.csv")):,} rows) ===')
    display(df.head(2))

=== orders (99,441 rows) ===

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,is_delivered,delivery_delay_days,is_delayed,purchase_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,-8.0,0,2017-10-02
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,1,-6.0,0,2018-07-24

=== order_items (112,650 rows) ===

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,is_valid_price,is_valid_freight
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29,True,True
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.9,19.93,True,True

=== products (32,951 rows) ===

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english,category_en
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,perfumery,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,art,art

=== customers (99,441 rows) ===

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,Franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,Sao Bernardo Do Campo,SP

=== reviews (99,224 rows) ===

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,is_valid_score
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59,True
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13,True